.github/workflows/ci.yml, lib/types/types.d.ts, lib/types/types.js, package-lock.json, package.json, src/types/types.ts
=> Updates from calls

lib/types/types.d.ts, src/types/types.ts
Adds some common types to be used in https://github.com/mattermost/mattermost-plugin-calls/pull/406
https://mattermost.atlassian.net/browse/MM-44707
=> [MM-44707] Add CallChannelState type

lib/types/types.d.ts, lib/utils/index.d.ts, lib/utils/index.js, src/types/types.ts, src/utils/index.ts, tsconfig.json
- The color utils in mobile aren't sufficient for what we need to do, so commonizing them for both mobile and webapp
- Related to: mobile: https://mattermost.atlassian.net/browse/MM-51228 and webapp: https://github.com/mattermost/mattermost-plugin-calls/pull/360
=> MM-51228 - Add color utils

lib/rtc_monitor.d.ts, lib/rtc_monitor.js, package-lock.json, package.json, src/rtc_monitor.ts
- Add mean opinion score threshold of 3.5
- Ref: https://github.com/mattermost/mattermost-mobile/pull/7304#discussion_r1175561001
- none
=> Add mos threshold

.github/workflows/ci.yml, babel.config.js, lib/rtc_peer.d.ts, lib/rtc_peer.js, lib/utils.d.ts, lib/utils.js, package-lock.json, package.json, src/rtc_peer.ts, src/utils.test.ts, src/utils.ts
PR adds implementation for removing tracks from the peer connection. This is meant when stopping screen sharing.
Will need to test this a bit before merging to make sure nothing unexpected breaks.
=> Implement `RTCPeer.removeTrack()`

lib/index.d.ts, lib/index.js, src/index.ts
- forgot to export it from the index
- none
=> Fix export of mosThreshold

lib/index.d.ts, lib/index.js, src/index.ts, src/utils/utils.test.ts
- Just moving the tests here in prep for moving the color code in the main plugin to use calls-common
- https://mattermost.atlassian.net/browse/MM-52340
=> MM-52340 - Consolidate color code

lib/types/types.d.ts, src/types/types.ts
- This simplifies some checks and makes more sense (bc order doesn't matter).
- https://mattermost.atlassian.net/browse/MM-52857
=> MM-52857 - Move from array to object

lib/types/types.d.ts, src/types/types.ts
- Now sending the call id on start, and filling in a missing field
- https://mattermost.atlassian.net/browse/MM-52857
=> MM-52857 - More type changes for dm/gm ringing

lib/types/types.d.ts, src/types/types.ts
Types changes for https://github.com/mattermost/mattermost-plugin-calls/pull/518
https://mattermost.atlassian.net/browse/MM-51852
=> [MM-51852] Multi-sessions support

lib/types/webrtc.d.ts, src/types/webrtc.ts
This should be optional as we have a default in place.
=> Make connTimeoutMs optional

lib/types/types.d.ts, src/types/types.ts
Updating the calls config type with the new `EnableTranscriptions` flag.
=> EnableTranscriptions

lib/types/types.d.ts, src/types/types.ts
Common type for captions that we'll include in the recording post props.
https://mattermost.atlassian.net/browse/MM-56089
=> [MM-56089] Caption type

lib/types/types.d.ts, src/types/types.ts
Adding some proper types for the props we can find in Calls posts.
https://github.com/mattermost/mattermost-plugin-calls/pull/606
https://mattermost.atlassian.net/browse/MM-56055
=> [MM-56055] Call posts props types

lib/types/types.d.ts, src/types/types.ts
Adding the payload type for the new `job_stop` websocket event.
https://mattermost.atlassian.net/browse/MM-56187
=> [MM-56187] Add JobStopData

lib/types/types.d.ts, src/types/types.ts
- Add LiveCaptions necessary for live captions feature
- https://mattermost.atlassian.net/browse/MM-56540
=> MM-56540 - Add LiveCaptions message

.eslintrc.json, lib/rtc_peer.js, lib/types/types.d.ts, package-lock.json, package.json, src/types/types.ts
- use `CallJobState` instead of `CallRecordingState`
- put the job type into `CallJobStateData`
- https://mattermost.atlassian.net/browse/MM-56540
=> MM-56540 - Type changes for live-captions-related refactoring

lib/types/types.d.ts, src/types/types.ts
- Needed by mobile for https://github.com/mattermost/mattermost-mobile/pull/7905
- https://mattermost.atlassian.net/browse/MM-57967
=> [MM-57967] Add HostControlsAllowed to the config

lib/types/types.d.ts, package-lock.json, package.json, src/types/types.ts
- Factoring out the host control msgs. It's not clean, but I chose to only send what we needed in each message (rather than too much just for the sake of a single "host control message" type).
- Bumping the version and I'll publish when this goes in, then I'll bump calls and mobile.
- https://mattermost.atlassian.net/browse/MM-57919
=> [MM-57919] Add host control message types

package.json
=> Dot release

lib/rtc_peer.js, lib/types/types.d.ts, lib/types/types.js, package-lock.json, src/types/types.ts
Adding `TranscribeAPI` config field after changes in https://github.com/mattermost/mattermost-plugin-calls/pull/786
https://mattermost.atlassian.net/browse/MM-57220
=> [MM-57220] Add TranscribeAPI to config

.github/workflows/ci.yml, lib/rtc_peer.d.ts, lib/rtc_peer.js, lib/types/types.d.ts, lib/types/webrtc.d.ts, src/rtc_peer.ts, src/types/types.ts, src/types/webrtc.ts
PR adds support for encoding tracks using multiple codecs.
https://mattermost.atlassian.net/browse/MM-52657
=> [MM-52657] AV1 support

.gitignore, lib/rtc_peer.d.ts, lib/rtc_peer.js, lib/types/dc_msg.d.ts, lib/types/dc_msg.js, src/dc_msg.test.ts, src/rtc_peer.ts, src/types/dc_msg.ts
Client-side companion of https://github.com/mattermost/rtcd/pull/170
https://mattermost.atlassian.net/browse/MM-62296
=> [MM-62296] Implement race free signaling through DC based lock

lib/types/types.d.ts, src/types/types.ts
We are exposing the full config to admins to add support for environment overrides.
https://github.com/mattermost/mattermost-plugin-calls/pull/1004
https://mattermost.atlassian.net/browse/MM-62732
=> [MM-62732] Expose full config to admins

lib/rtc_peer.js, lib/types/types.d.ts, lib/types/webrtc.d.ts, lib/utils.d.ts, lib/utils.js, package-lock.json, package.json, src/rtc_peer.test.ts, src/rtc_peer.ts, src/types/types.ts, src/types/webrtc.ts, src/utils.test.ts, src/utils.ts
PR adds a new, default false, `dcLocking` config option to `RTCPeer`. This should be set accordingly based on backend version checks, for which we include some utility helpers.
https://mattermost.atlassian.net/browse/MM-63889
=> [MM-63889] Add dcLocking option and version utils

lib/types/types.d.ts, src/types/types.ts
Companion to https://github.com/mattermost/mattermost-plugin-calls/pull/998
https://mattermost.atlassian.net/browse/MM-63550
=> [MM-63550] Remove deprecated types
